controller_manager:
  ros__parameters:
      update_rate: 100
      use_sim_time: true

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    use_stamped_vel: true
    left_wheel_names: ["fl_joint", "rl_joint"]
    right_wheel_names: ["fr_joint", "rr_joint"]

    wheel_separation: 0.064
    wheel_radius: 0.098

    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    enable_odom_tf: true
    publish_rate: 100.0

    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.y.max_velocity: 1.0
    linear.y.min_velocity: -1.0
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0

          